# Generated by Django 4.1.5 on 2023-01-10 06:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idCategoria', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Categoria')),
                ('nombreCategoria', models.CharField(max_length=70, verbose_name='Nombre de la Categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Plato',
            fields=[
                ('idPlato', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Plato')),
                ('nombrePlato', models.CharField(max_length=70, verbose_name='Nombre del Plato')),
                ('valorPlato', models.IntegerField(verbose_name='Valor del Plato')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
