# Generated by Django 4.1.5 on 2023-01-13 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_usuario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('idProducto', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Producto')),
                ('nombreProducto', models.CharField(max_length=70, verbose_name='Nombre del Producto')),
                ('cantidadProducto', models.CharField(max_length=70, verbose_name='Cantidad de Producto')),
            ],
        ),
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('idFecha', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Fecha')),
                ('nombreFecha', models.CharField(max_length=70, verbose_name='Valor de la Fecha')),
            ],
        ),
        migrations.CreateModel(
            name='Hora',
            fields=[
                ('idHora', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de hora')),
                ('nombrehora', models.CharField(max_length=70, verbose_name='Valor de la hora')),
            ],
        ),
        migrations.CreateModel(
            name='Reservacion',
            fields=[
                ('idReservacion', models.IntegerField(primary_key=True, serialize=False, verbose_name='id de Reserva')),
                ('nombreReservacion', models.CharField(max_length=70, verbose_name='Nombre del Reservante')),
                ('fecha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fecha')),
                ('hora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.hora')),
            ],
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
