# Generated by Django 4.1.5 on 2023-01-13 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_bodega_fecha_hora_reservacion_delete_usuario'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hora',
            old_name='nombrehora',
            new_name='nombreHora',
        ),
    ]
